version: '3.8'

services:
  endpoint-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/endpoint-api-db

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  web-app:
    build:
      context: ../ScrapSnapWEB
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE_URL: http://localhost:3000
    ports:
      - "80:80"

volumes:
  mongo-data:
