name: scrap-snap
services:
  endpoint-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/endpoint-api-db

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  minio:
    command: 'server /data --console-address ":9001"'
    env_file:
      - .env
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data

  web-app:
    build:
      context: ../ScrapSnapWEB
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE_URL: http://localhost:3000
    ports:
      - "80:80"

volumes:
  mongo-data:
  minio-data:
